### ISSUE TITLE
Tilde fenced code blocks

### ISSUE THREAD

**Issue by cup** [shushcat/vim-minimd#1]
Fenced code blocks are defined as:

> A code fence is a sequence of at least three consecutive backtick characters
> (<code>&#x60;</code>) or tildes (`~`).

This is in the current Markdown spec (Apr 2019), and even back to the oldest
spec (Oct 2014):

- https://spec.commonmark.org/0.29#fenced-code-blocks
- https://spec.commonmark.org/0.5#fenced-code-blocks

However Vim-MiniMd currently only recognizes backticks for fenced code block:

https://github.com/shushcat/vim-minimd/blob/ccded8d1988b95703d1ce19cf407d51ae895d894/syntax/minimd.vim#L27

**Comment by shushcat** [comment]
Hey, thanks for pointing this out---it should be fixed now.
