### ISSUE TITLE
Word count bug

### ISSUE THREAD

**Issue by akemrir** [shushcat/vim-minimd#2]
I am using vim-minimd latest from github, on archlinux:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Zadane łaty: 1-1704

And I found a bug in word counting function about too many arguments.

```
Wykryto błąd podczas przetwarzania BufEnter Autokomend dla "*"..function minimd#UpdateWordCount:
wiersz    7:
E684: Indeks listy poza zakresem: 11
E116: Zbyt wiele argumentów dla funkcji str2nr(split(v:statusmsg)[11])
```
It is present no matter which file I open, even with new empty markdown buffer.

**Comment by shushcat** [comment]
Thanks for the report.  The word count function was more complicated than it had to be, and I've simplified it now, which should fix your problem :smile:.  Let me know if it works, and I'll close this issue.

**Comment by akemrir** [comment]
Fix worked :) Thanks.
