### ISSUE TITLE
Space to Close Section No Longer Works

### ISSUE THREAD

**Issue by ossie-git** [shushcat/vim-minimd#4]
After upgrading to the latest version (d3846c023c112350bdd0637e79494d132c055586), the space key no longer works to close the section I am in. So if I am in the middle of a section and want to close it, I now have to move to the header of the section and then press the space key to close the section. Prior to the latest updates, I could simply press space and it would close the section for me, regardless of where in the section I was. Thanks

**Comment by shushcat** [comment]
Hey, thanks for testing things.  The problem should be fixed as of a0380fb---please do let me know if it isn't.

**Comment by ossie-git** [comment]
Thanks @shushcat
