### ISSUE TITLE
[Feature Request] Fenced Code Block Syntax Highlighting

### ISSUE THREAD

**Issue by ossie-git** [shushcat/vim-minimd#6]
Hi,

I'm not sure how easy it would be to add this but tpope's [vim-markdown](https://github.com/tpope/vim-markdown) plugin has support for this which is very nice :)

**Comment by shushcat** [comment]
I am worried that implementing this might be an enormous faff, but agree that it would be nice to have provided it didn't slow things down too much.

For my own reference:

- [The relevant portion of the default Markdown syntax file](https://github.com/tpope/vim-markdown/blob/addd5abaa66f015802ec351cd67893f6e521751e/syntax/markdown.vim#L23).
- [A StackExchange answer about embedding highlighting for other syntaxes in a Vim syntax file](https://tex.stackexchange.com/questions/18904/which-is-the-best-editor-for-luatex/18916#18916).

**Comment by ossie-git** [comment]
No problem. I just installed tpope's plugin and defined a simple macro to quickly switch between between the two by changing the filetype. So I'm in minimd most of the time but if I run into a code snippet, I switch to tpope's plugin and then switch back.

**Comment by shushcat** [comment]
As of 05202d111398a6fadf075e415b5ceae43476e8e3, you can set the option `g:default_markdown_syntax = 1` to use MiniMD's folding and navigation bits with the default Markdown syntax 😄

**Comment by ossie-git** [comment]
That's great. Thanks a lot @shushcat 😃
