### ISSUE TITLE
Header Bindings [] Mess with Spell Checking

### ISSUE THREAD

**Issue by ossie-git** [shushcat/vim-minimd#7]
If you enable spell checking and then try to use `[s` or `]s` to jump between spelling errors, it doesn't work due to minimd overriding the default mapping. Is there an option to disable this? Thanks

**Comment by shushcat** [comment]
I've changed the default secondary bindings for header motion to `[h` and `]h`, which shouldn't interfere with any Vim defaults.  If you want to disable those bindings, or to set different motion bindings, you can put something like the following in `~/.vim/plugin/minimd.vim`:

```vim
" Unset a binding
unmap [h
" Move to the next header with 'H', and to the previous one with 'h'
nmap h :MiniMDPrev<CR>
nmap H :MiniMDNext<CR>
```

**Comment by ossie-git** [comment]
Just tested it and it works. Thanks a lot @shushcat 😀
